mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  db: test
  connMaxLifeTime: 60
  maxIdleConn: 60
  maxOpenConn: 10

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:
  maxRetries: 3
  minIdleConns: 5
  poolSize: 10