app:
  name: hello-go
  version: v1.0.0
  port: 9999
  api-prefix: /api
  log-file: logs/hello-go.log

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  db: hello-go
  params: charset=utf8&parseTime=True&loc=Local
  table-prefix: cs_
  singular-table: true
  max-idle-conns: 60
  max-open-conns: 20
  log-mode: info

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:
  max-retries: 3
  max-idle-conns: 60
  pool-size: 10